version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flaskBlog
hooks:
  BeforeInstall:
    - location: scripts/install_docker_compose.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_docker_compose.sh
      timeout: 300
      runas: root

